heat_template_version: 2013-05-23
# This template will not work for general NeCTAR users
# You need to have been granted acces rights to Trove for this to work...


description: >
  NeCTAR Sample Template that creates a Trove database instance, then use Liquibase to
  inflate the database with table information.
  Be warned: this template will not work if you don't have access rights to Trove!


parameters:
  db_password:
    type: string
    label: Database User Password
    description: Password for the database user (must be > 6 characters long).
    hidden: true
    constraints:
      - length: { min: 6}
        description: Passwords must be at least 6 characters in length.

  db_user:
    type: string
    label: Database User Name
    description: The name of the database user.

  db_name:
    type: string
    label: Database Name
    description: The name of the database that you want to create in the Trove instance.
    constraints:
      - length: { min: 4}
        description: The database must be at least 4 characters in length.

  trove_instance_name:
    type: string
    label: Trove Instance Name
    description: The name of the Trove instance that you want to create.
    constraints:
      - length: { min: 4}
        description: The instance name must be at least 4 characters in length.


resources:
  sample_database:
    type: OS::Trove::Instance
    # Currently trove lives in its own availability_zone, so do not use the availability_zone attribute.
    properties:
      name: { get_param: trove_instance_name}
      databases: [{ name: { get_param: db_name} }, ]
      flavor: 512MB Instance
      size: 1
      users: [{ password: { get_param: db_password }, name: { get_param: db_user }, databases: [ { get_param: db_name} ] }, ]


outputs:
  host_name:
    description: The host name of the data store.
    value: { get_attr: [sample_database, hostname] }
  host_href:
    description: The href of the data store.
    value: { get_attr: [sample_database, href] }
